[package]
authors = ["Gio d'Amelio <giodamelio@gmail.com>"]
description = "Adds boxes around stdin. Optionally adds a title"
documentation = "https://github.com/giodamelio/little_boxes"
homepage = "https://github.com/giodamelio/little_boxes"
license = "MIT"
name = "little_boxes"
repository = "https://github.com/giodamelio/little_boxes"
version = "1.6.0"

[dependencies]
docopt = "0.8.1"
regex = "0.2.1"
serde = "1.0.12"
serde_derive = "1.0.12"
